swagger: '2.0'
info:
  version: 1.0.0
  title: Api service utilisateur
  description: Api de gestion des utilisateurs et operations bancaires
  contact:
    name: Cyril Marchive
    url: https://github.com/langston8182
    email: cyril.marchive@gmail.com

host: localhost:8100
basePath: /
tags:
  - name: utilisateurs
    description: Gestion des utilisateurs
  - name: operations
    description: Gestion des operations
  - name: operationsPermanentes
    description: Gestion des operations permanentes

schemes:
  - http
  - https

paths:
  /utilisateurs/:
    get:
      tags:
        - utilisateurs
      summary: Liste les utilisateurs
      operationId: listerUtilisateur
      description: ""
      produces:
        - "application/json"
        - "application/xml"
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/UtilisateurDtos'
        401:
          description: Unauthorized
        403:
          description: Forbidden
      security:
        - auth:
            - "admin"
            - "openid"
    post:
      tags:
        - utilisateurs
      summary: Creer un utilisateur
      operationId: sauvegarderUtilisateur
      description: ""
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/json"
        - "application/xml"
      parameters:
        - in: body
          name: body
          description: Utilisateur a ajouter (Sans le Id)
          required: true
          schema:
            $ref: '#/definitions/UtilisateurDto'
      responses:
        409:
          description: Utilisateur deja present
        401:
          description: Unauthorized
        403:
          description: Forbidden
        405:
          description: Elements en entree invalides
        200:
          description: OK
          schema:
            $ref: '#/definitions/UtilisateurDto'
      security:
        - auth:
            - "admin"
            - "openid"
    put:
      tags:
        - utilisateurs
      summary: Modifier un utilisateur
      operationId: modifierUtilisateur
      description: ""
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/json"
        - "application/xml"
      parameters:
        - in: body
          name: body
          description: Utilisateur a modifier
          required: true
          schema:
            $ref: '#/definitions/UtilisateurDto'
      responses:
        404:
          description: Utilisateur non trouve
        401:
          description: Unauthorized
        403:
          description: Forbidden
        405:
          description: Elements en entree invalides
        200:
          description: OK
          schema:
            $ref: '#/definitions/UtilisateurDto'
      security:
        - auth:
            - "admin"
            - "openid"
    delete:
      tags:
        - utilisateurs
      summary: Supprimer un utilisateur
      operationId: supprimerUtilisateur
      description: ""
      consumes:
        - "application/json"
      parameters:
        - in: body
          name: body
          description: Utilisateur a supprimer
          required: true
          schema:
            $ref: '#/definitions/UtilisateurDto'
      responses:
        204:
          description: OK aucun contenu
        401:
          description: Unauthorized
        403:
          description: Forbidden
        405:
          description: Elements en entree invalides
      security:
        - auth:
            - "admin"
            - "openid"

  /utilisateurs:
    get:
      tags:
        - utilisateurs
      summary: Recuperer un utilisateur par son email
      operationId: recupererUtilisateurParEmail
      description: ""
      produces:
        - "application/json"
        - "application/xml"
      parameters:
        - in: query
          name: email
          type: string
          description: Email utilisateur
      responses:
        404:
          description: Utilisateur non trouve
        401:
          description: Unauthorized
        403:
          description: Forbidden
        200:
          description: OK
          schema:
            $ref: '#/definitions/UtilisateurDto'
      security:
        - auth:
            - "admin"
            - "openid"

  /utilisateurs/{idUtilisateur}/operations-permanentes/:
    get:
      tags:
        - utilisateurs
      summary: Liste les operations permanentes d'un utilisateur
      operationId: listerOperationPermanenteUtilisateur
      description: ""
      produces:
        - "application/json"
        - "application/xml"
      parameters:
        - name: idUtilisateur
          in: path
          description: Identifiant de l'utilisateur
          type: string
          required: true
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/OperationPermanenteDtos'
        401:
          description: Unauthorized
        403:
          description: Forbidden
      security:
        - auth:
            - "admin"
            - "openid"

  /utilisateurs/{idUtilisateur}/operations/:
    get:
      tags:
        - utilisateurs
      summary: Liste les operations d'un utilisateur
      operationId: listerOperationUtilisateur
      description: ""
      produces:
        - "application/json"
        - "application/xml"
      parameters:
        - name: idUtilisateur
          in: path
          description: Identifiant de l'utilisateur
          type: string
          required: true
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/OperationDtos'
        401:
          description: Unauthorized
        403:
          description: Forbidden
      security:
        - auth:
            - "admin"
            - "openid"

  /utilisateurs/{id}:
    get:
      tags:
        - utilisateurs
      summary: Recupere un utilisateur par son identifiant
      operationId: recupererUtilisateur
      description: ""
      produces:
        - "application/json"
        - "application/xml"
      parameters:
        - name: id
          in: path
          description: Identifiant de l"utilisateur
          type: string
          required: true
      responses:
        404:
          description: Utilisateur non trouve
        401:
          description: Unauthorized
        403:
          description: Forbidden
        200:
          description: OK
          schema:
            $ref: '#/definitions/UtilisateurDto'
      security:
        - auth:
            - "admin"
            - "openid"

  /utilisateurs/{idUtilisateur}/operations-permanentes/{idOperationPermanente}:
    get:
      tags:
        - utilisateurs
      summary: Recuperer une operation permanente par son utilisateur et son identifiant
      operationId: recupererOperationPermanenteParUtilisateur
      description: ""
      produces:
        - "application/json"
        - "application/xml"
      parameters:
        - name: idUtilisateur
          description: Identifiant de l'utilisateur
          in: path
          type: string
          required: true
        - name: idOperationPermanente
          description: Identifiant de l'operation permanente
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/OperationPermanenteDto'
        404:
          description: Utilisateur non trouve
        401:
          description: Unauthorized
        403:
          description: Forbidden
      security:
        - auth:
            - "admin"
            - "openid"

  /utilisateurs/{idUtilisateur}/operations/{idOperation}:
    get:
      tags:
        - utilisateurs
      summary: Recuperer une operation par son utilisateur et son identifiant
      operationId: recupererOperationParUtilisateur
      description: ""
      produces:
        - "application/json"
        - "application/xml"
      parameters:
        - name: idUtilisateur
          description: Identifiant de l'utilisateur
          in: path
          type: string
          required: true
        - name: idOperation
          description: Identifiant de l'operation
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/OperationDto'
        404:
          description: Utilisateur non trouve
        401:
          description: Unauthorized
        403:
          description: Forbidden
      security:
        - auth:
            - "admin"
            - "openid"

  /operations/:
    post:
      tags:
        - operations
      summary: Ajoute une operation a un utilisateur
      operationId: ajouterOperationAUtilisateur
      description: "Utilise le jeton JWT pour connaitre l'utilisateur a travers `Principal`"
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/json"
        - "application/xml"
      parameters:
        - in: body
          name: body
          description: Operation a ajouter
          required: true
          schema:
            $ref: '#/definitions/OperationDto'
      responses:
        404:
          description: Utilisateur non trouve
        401:
          description: Unauthorized
        403:
          description: Forbidden
        405:
          description: Elements en entree invalides
        200:
          description: OK
          schema:
            $ref: '#/definitions/OperationDto'
      security:
        - auth:
            - "admin"
            - "openid"
    put:
      tags:
        - operations
      summary: Modifier une operation
      operationId: modifierOperationUtilisateur
      description: ""
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/json"
        - "application/xml"
      parameters:
        - in: body
          name: body
          description: Operation a modifier
          required: true
          schema:
            $ref: '#/definitions/OperationDto'
      responses:
        404:
          description: Utilisateur non trouve
        401:
          description: Unauthorized
        403:
          description: Forbidden
        405:
          description: Elements en entree invalides
        200:
          description: OK
          schema:
            $ref: '#/definitions/OperationDto'
      security:
        - auth:
            - "admin"
            - "openid"
    delete:
      tags:
        - operations
      summary: Supprimer une operation
      operationId: supprimerOperationUtilisateur
      description: ""
      consumes:
        - "application/json"
        - "application/xml"
      parameters:
        - in: body
          name: body
          description: Operation a supprimer
          required: true
          schema:
            $ref: '#/definitions/OperationDto'
      responses:
        204:
          description: OK aucun contenu
        401:
          description: Unauthorized
        403:
          description: Forbidden
        405:
          description: Elements en entree invalides
      security:
        - auth:
            - "admin"
            - "openid"

  /operations-permanentes/:
    post:
      tags:
        - operationsPermanentes
      summary: Ajoute une operation permanente a un utilisateur
      description: "Utilise le jeton JWT pour connaitre l'utilisateur a travers `Principal`"
      operationId: ajouterOperationPermanenteAUtilisateur
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/json"
        - "application/xml"
      parameters:
        - in: body
          name: body
          description: Operation permanente a ajouter (Sans le Id et l'utilisateur)
          required: true
          schema:
            $ref: '#/definitions/OperationPermanenteDto'
      responses:
        404:
          description: Utilisateur non trouve
        401:
          description: Unauthorized
        403:
          description: Forbidden
        405:
          description: Elements en entree invalides
        200:
          description: OK
          schema:
            $ref: '#/definitions/OperationPermanenteDto'
      security:
        - auth:
            - "admin"
            - "openid"
    put:
      tags:
        - operationsPermanentes
      summary: Modifier une operation permanente
      description: ""
      operationId: modifierOperationPermanenteUtilisateur
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/json"
        - "application/xml"
      parameters:
        - in: body
          name: body
          description: Operation permanente a modifier
          required: true
          schema:
            $ref: '#/definitions/OperationPermanenteDto'
      responses:
        404:
          description: Utilisateur non trouve
        401:
          description: Unauthorized
        403:
          description: Forbidden
        405:
          description: Elements en entree invalides
        200:
          description: OK
          schema:
            $ref: '#/definitions/OperationPermanenteDto'
      security:
        - auth:
            - "admin"
            - "openid"
    delete:
      tags:
        - operationsPermanentes
      summary: Supprimer une operation permanente
      description: ""
      operationId: supprimerOperationPermanenteUtilisateur
      consumes:
        - "application/json"
        - "application/xml"
      parameters:
        - in: body
          name: body
          description: Operation permanente a supprimer
          required: true
          schema:
            $ref: '#/definitions/OperationPermanenteDto'
      responses:
        204:
          description: OK aucun contenu
        401:
          description: Unauthorized
        403:
          description: Forbidden
        405:
          description: Elements en entree invalides
      security:
        - auth:
            - "admin"
            - "openid"

securityDefinitions:
  auth:
    type: oauth2
    authorizationUrl: "https://dev-847930.okta.com/oauth2/default/v1/authorize"
    tokenUrl: "https://dev-847930.okta.com/oauth2/default/v1/token"
    flow: accessCode
    scopes:
      admin: "pour les operation d'administration"
      openid: "pour les operation liee a Okta"

definitions:
  ResourceSupport:
    type: object
    required:
      - "className"
    discriminator: "className"
    properties:
      className:
        type: "string"

  UtilisateurDto:
    allOf:
      - $ref: '#/definitions/ResourceSupport'
      - type: object
        required:
          - email
          - nom
          - prenom
        properties:
          identifiant:
            type: string
            description: Identifiant de l'utilisateur
            example: "1"
          nom:
            type: string
            description: Nom de l'utilisateur
            example: "Marchive"
          prenom:
            type: string
            description: Prenom de l'utilisateur
            example: "Cyril"
          email:
            type: string
            description: Email de l'utilisateur
            example: "cyril.marchive@gmail.com"

  UtilisateurDtos:
    allOf:
      - $ref: '#/definitions/ResourceSupport'
      - type: object
        required:
          - utilisateurDtos
        properties:
          utilisateurDtos:
            type: array
            items:
              $ref: '#/definitions/UtilisateurDto'

  OperationPermanenteDto:
    allOf:
      - $ref: '#/definitions/ResourceSupport'
      - type: object
        required:
          - intitule
          - jour
          - prix
        properties:
          identifiant:
            type: string
            description: Identifiant de l'operation permanente
            example: 1
          intitule:
            type: string
            description: Intitule de l'operation permanente
            example: Videotron
          prix:
            type: number
            description: Prix de l'operation permanente
            example: 60.0
          jour:
            type: integer
            description: Jour du mois de l'operation permanente
            example: "12"
          utilisateurDto:
            $ref: '#/definitions/UtilisateurDto'

  OperationPermanenteDtos:
    allOf:
      - $ref: '#/definitions/ResourceSupport'
      - type: object
        required:
          - operationPermanenteDtos
        properties:
          operationPermanenteDtos:
            type: array
            items:
              $ref: '#/definitions/OperationPermanenteDto'

  OperationDto:
    allOf:
      - $ref: '#/definitions/ResourceSupport'
      - type: object
        required:
          - dateOperation
          - intitule
          - prix
        properties:
          identifiant:
            type: string
            description: Identifiant de l'operation
            example: 1
          intitule:
            type: string
            description: Intitule de l'operation
            example: Hydro Quebec
          prix:
            type: number
            description: Prix de l'operation
            example: 100.0
          dateOperation:
            type: string
            format: date
            description: Date de l'operation au format *yyyy-dd-MM*
            example: "2017-07-21"
          utilisateurDto:
            $ref: '#/definitions/UtilisateurDto'

  OperationDtos:
    allOf:
      - $ref: '#/definitions/ResourceSupport'
      - type: object
        required:
          - operationDtos
        properties:
          operationDtos:
            type: array
            items:
              $ref: '#/definitions/OperationDto'